version: '3.8'

services:
  psql:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - '8181:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'

volumes:
  db-data: